# Generated by Django 6.0.4 on 2026-04-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(choices=[('hyundai', '현대카드(용돈)'), ('shinhan', '신한카드(고정비)'), ('incident', '사건비통장')], default='hyundai', max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_fuel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='liters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_per_liter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('expense', '지출'), ('income', '환급/입금'), ('non_expense', '비지출(지원)')], default='expense', max_length=15),
        ),
    ]
