# Generated by Django 6.0.4 on 2026-04-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_transaction_account_type_transaction_is_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(choices=[('hyundai', '현대카드(용돈)'), ('shinhan', '신한카드(고정비)'), ('incident', '사건비통장'), ('cash', '현금'), ('transfer', '이체')], default='hyundai', max_length=15),
        ),
    ]
