# Generated by Django 6.0.4 on 2026-04-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detail_category',
            field=models.CharField(choices=[('외식', '외식'), ('커피', '커피'), ('주유', '주유'), ('쇼핑', '쇼핑'), ('병원', '병원'), ('고정비', '고정비'), ('생활', '생활'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
