# Generated by Django 4.2.30 on 2026-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_transaction_detail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(choices=[('hyundai', '현대카드(용돈)'), ('shinhan', '신한카드(고정비)'), ('incident', '사건비통장'), ('cash_transfer', '현금/이체')], default='hyundai', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
