# Generated by Django 4.2.30 on 2026-04-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_checklist_amount_alter_checklist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(choices=[('hyundai', '현대카드(용돈)'), ('shinhan', '신한카드(고정비)'), ('incident', '사건비통장'), ('cash_transfer', '현금/이체'), ('living', '생활비통장')], default='hyundai', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('expense', '지출'), ('income', '환급/입금'), ('non_expense', '비지출/이동')], default='expense', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='detail_category',
            field=models.CharField(choices=[('외식', '외식'), ('커피', '커피'), ('주유', '주유'), ('쇼핑', '쇼핑'), ('병원', '병원'), ('고정비', '고정비'), ('생활', '생활'), ('비상금', '비상금'), ('현금', '현금'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
