# Generated by Django 4.2.30 on 2026-04-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_transaction_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='detail_category',
            field=models.CharField(choices=[('정기입금', '정기입금'), ('추가수입', '추가수입'), ('환급', '환급'), ('식비', '식비'), ('영양식품', '영양식품'), ('주거비', '주거비'), ('생활용품', '생활용품'), ('가족용돈', '가족용돈'), ('자동차관련', '자동차관련'), ('쇼핑', '쇼핑'), ('여행경비', '여행경비'), ('병원비', '병원비'), ('비상금', '비상금'), ('현금', '현금'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
