# Generated by Django 4.2.30 on 2026-04-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_transaction_detail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='detail_category',
            field=models.CharField(choices=[('정기입금', '정기입금'), ('추가수입', '추가수입'), ('환급', '환급'), ('식비', '식비'), ('영양식품', '영양식품'), ('주거비', '주거비'), ('생활용품', '생활용품'), ('가족용돈', '가족용돈'), ('자동차관련', '자동차관련'), ('쇼핑', '쇼핑'), ('여행관련', '여행관련'), ('카페/간식', '카페/간식'), ('선물', '선물'), ('문화활동', '문화활동'), ('병원/건강', '병원/건강'), ('비상금 넣기', '비상금 넣기'), ('비상금 빼기', '비상금 빼기'), ('현금 넣기', '현금 넣기'), ('현금 쓰기', '현금 쓰기'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
