# Generated by Django 4.2.30 on 2026-04-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
