# Generated by Django 4.2.30 on 2026-05-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_memo_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='detail_category',
            field=models.CharField(choices=[('외식', '외식'), ('커피/간식', '커피/간식'), ('배달', '배달'), ('장보기', '장보기'), ('쇼핑', '쇼핑'), ('생활용품', '생활용품'), ('미용', '미용'), ('주유', '주유'), ('교통', '교통'), ('고속도로', '고속도로'), ('관리비', '관리비'), ('보험', '보험'), ('통신비', '통신비'), ('구독', '구독'), ('병원비', '병원비'), ('경조사', '경조사'), ('선물', '선물'), ('여행', '여행'), ('정산', '정산'), ('고정비', '고정비'), ('환급', '환급'), ('용돈', '용돈'), ('정산', '정산'), ('판매금', '판매금'), ('기타수입', '기타수입'), ('정기입금', '정기입금'), ('추가수입', '추가수입'), ('환급', '환급'), ('식비', '식비'), ('영양식품', '영양식품'), ('주거비', '주거비'), ('가족용돈', '가족용돈'), ('자동차관련', '자동차관련'), ('여행관련', '여행관련'), ('카페/간식', '카페/간식'), ('문화활동', '문화활동'), ('병원/건강', '병원/건강'), ('비상금 넣기', '비상금 넣기'), ('비상금 빼기', '비상금 빼기'), ('비상금 직접입금', '비상금 직접입금'), ('현금 넣기', '현금 넣기'), ('현금 쓰기', '현금 쓰기'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
